# Generated by Django 4.1.5 on 2023-01-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=255, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=128, unique=True, verbose_name='이름'),
        ),
    ]
