# Generated by Django 4.1.5 on 2023-01-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_password_alter_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='passwordcheck',
            field=models.CharField(default='', max_length=255, verbose_name='비밀번호확인'),
            preserve_default=False,
        ),
    ]
