# Generated by Django 4.1.5 on 2023-01-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_password_member_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(null=True, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='이름'),
        ),
    ]
