# Generated by Django 4.1.5 on 2023-01-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
